name: BUILD and Deploy - DEV
run-name: CICD - PROJETO-CALCULADORA - DEV - ${{ github.run_number }} - ${{ github.event.pull_request.title }}

on:
  pull_request:
    types:
      - closed
    branches:
      - development

env:
  AWS_REGION: us-east-2
  ROLE_TO_ASSUME: arn:aws:iam::431591413306:role/role-github-horas
  ECR_REPOSITORY: calculadorafernando

permissions:
  contents: read
  id-token: write

jobs:
  build-image:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    outputs:
      image_builded: ${{ steps.image-outputs.outputs.image }}
      short_sha: ${{ steps.sha-output.outputs.sha }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set short sha
        id: sha-output
        run: |
          echo "sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: "Configure AWS Providers"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ecr-${{ steps.sha-output.outputs.sha }}-push-image
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: "no"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        id: build-image-docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          provenance: false
          target: build

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Image Output
        id: image-outputs
        run: |
          echo "image=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: validate env
        run: |
          echo "${{ steps.image-outputs.outputs.image }}"
          echo "${{ steps.sha-output.outputs.sha }}"
 
  deployment:
    runs-on: ubuntu-latest
    needs: build-image
    env:
      CLUSTER: calculadora      #  < ----------------------- INformação cluster ----------------------- >
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: "Configure AWS Providers"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: task-${{ needs.build-image.outputs.short_sha }}
          aws-region: ${{ env.AWS_REGION }}



      #  < ----------------------- INformação service ----------------------- >
      - name: Service Deployment - service-calculadora-fernando-dev
        uses: ./.github/workflows/actions/custom-deploy-aws
        with:
          service-name: service-calculadora-fernando-dev
          task-definition-path: .github/workflows/task-definitions/dev/task-definition-dev.json
          cluster-name: ${{ env.CLUSTER }}
          container-name: container-calculadora-80-tcp
          image-id: ${{ needs.build-image.outputs.image_builded }}